// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: phonebook.proto

// PhoneBook Service
//
// PhoneBook Service API consists of 3 services to find, reserve,
// and assign a phone number.

package phonebook

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *FindOneRequest) Validate() error {
	if this.PhoneNumber == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("PhoneNumber", fmt.Errorf(`value '%v' must not be an empty string`, this.PhoneNumber))
	}
	return nil
}
func (this *FindOneResponse) Validate() error {
	return nil
}
func (this *ReserveRequest) Validate() error {
	return nil
}
func (this *ReserveResponse) Validate() error {
	return nil
}
func (this *AssignRequest) Validate() error {
	if this.PhoneNumber == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("PhoneNumber", fmt.Errorf(`value '%v' must not be an empty string`, this.PhoneNumber))
	}
	if this.RefId == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("RefId", fmt.Errorf(`value '%v' must not be an empty string`, this.RefId))
	}
	return nil
}
func (this *AssignResponse) Validate() error {
	return nil
}
