// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phonebook.proto

// PhoneBook Service
//
// PhoneBook Service API consists of 3 services to find, reserve,
// and assign a phone number.

package phonebook

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ---- Find
type FindOneRequest struct {
	// Further validation can include regex.
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOneRequest) Reset()         { *m = FindOneRequest{} }
func (m *FindOneRequest) String() string { return proto.CompactTextString(m) }
func (*FindOneRequest) ProtoMessage()    {}
func (*FindOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{0}
}

func (m *FindOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneRequest.Unmarshal(m, b)
}
func (m *FindOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneRequest.Marshal(b, m, deterministic)
}
func (m *FindOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneRequest.Merge(m, src)
}
func (m *FindOneRequest) XXX_Size() int {
	return xxx_messageInfo_FindOneRequest.Size(m)
}
func (m *FindOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneRequest proto.InternalMessageInfo

func (m *FindOneRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type FindOneResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOneResponse) Reset()         { *m = FindOneResponse{} }
func (m *FindOneResponse) String() string { return proto.CompactTextString(m) }
func (*FindOneResponse) ProtoMessage()    {}
func (*FindOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{1}
}

func (m *FindOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneResponse.Unmarshal(m, b)
}
func (m *FindOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneResponse.Marshal(b, m, deterministic)
}
func (m *FindOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneResponse.Merge(m, src)
}
func (m *FindOneResponse) XXX_Size() int {
	return xxx_messageInfo_FindOneResponse.Size(m)
}
func (m *FindOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneResponse proto.InternalMessageInfo

func (m *FindOneResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

// ---- Reserve
type ReserveRequest struct {
	AreaCode             int32    `protobuf:"varint,1,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveRequest) Reset()         { *m = ReserveRequest{} }
func (m *ReserveRequest) String() string { return proto.CompactTextString(m) }
func (*ReserveRequest) ProtoMessage()    {}
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{2}
}

func (m *ReserveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveRequest.Unmarshal(m, b)
}
func (m *ReserveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveRequest.Marshal(b, m, deterministic)
}
func (m *ReserveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveRequest.Merge(m, src)
}
func (m *ReserveRequest) XXX_Size() int {
	return xxx_messageInfo_ReserveRequest.Size(m)
}
func (m *ReserveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveRequest proto.InternalMessageInfo

func (m *ReserveRequest) GetAreaCode() int32 {
	if m != nil {
		return m.AreaCode
	}
	return 0
}

type ReserveResponse struct {
	PhoneNumbers         []string `protobuf:"bytes,1,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	RefId                string   `protobuf:"bytes,2,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveResponse) Reset()         { *m = ReserveResponse{} }
func (m *ReserveResponse) String() string { return proto.CompactTextString(m) }
func (*ReserveResponse) ProtoMessage()    {}
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{3}
}

func (m *ReserveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveResponse.Unmarshal(m, b)
}
func (m *ReserveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveResponse.Marshal(b, m, deterministic)
}
func (m *ReserveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveResponse.Merge(m, src)
}
func (m *ReserveResponse) XXX_Size() int {
	return xxx_messageInfo_ReserveResponse.Size(m)
}
func (m *ReserveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveResponse proto.InternalMessageInfo

func (m *ReserveResponse) GetPhoneNumbers() []string {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

func (m *ReserveResponse) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

// ---- Assign
type AssignRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	RefId                string   `protobuf:"bytes,3,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignRequest) Reset()         { *m = AssignRequest{} }
func (m *AssignRequest) String() string { return proto.CompactTextString(m) }
func (*AssignRequest) ProtoMessage()    {}
func (*AssignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{4}
}

func (m *AssignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignRequest.Unmarshal(m, b)
}
func (m *AssignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignRequest.Marshal(b, m, deterministic)
}
func (m *AssignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignRequest.Merge(m, src)
}
func (m *AssignRequest) XXX_Size() int {
	return xxx_messageInfo_AssignRequest.Size(m)
}
func (m *AssignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssignRequest proto.InternalMessageInfo

func (m *AssignRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AssignRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *AssignRequest) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

type AssignResponse struct {
	Assigned             bool     `protobuf:"varint,1,opt,name=assigned,proto3" json:"assigned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignResponse) Reset()         { *m = AssignResponse{} }
func (m *AssignResponse) String() string { return proto.CompactTextString(m) }
func (*AssignResponse) ProtoMessage()    {}
func (*AssignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{5}
}

func (m *AssignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignResponse.Unmarshal(m, b)
}
func (m *AssignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignResponse.Marshal(b, m, deterministic)
}
func (m *AssignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignResponse.Merge(m, src)
}
func (m *AssignResponse) XXX_Size() int {
	return xxx_messageInfo_AssignResponse.Size(m)
}
func (m *AssignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AssignResponse proto.InternalMessageInfo

func (m *AssignResponse) GetAssigned() bool {
	if m != nil {
		return m.Assigned
	}
	return false
}

func init() {
	proto.RegisterType((*FindOneRequest)(nil), "phonebook.FindOneRequest")
	proto.RegisterType((*FindOneResponse)(nil), "phonebook.FindOneResponse")
	proto.RegisterType((*ReserveRequest)(nil), "phonebook.ReserveRequest")
	proto.RegisterType((*ReserveResponse)(nil), "phonebook.ReserveResponse")
	proto.RegisterType((*AssignRequest)(nil), "phonebook.AssignRequest")
	proto.RegisterType((*AssignResponse)(nil), "phonebook.AssignResponse")
}

func init() { proto.RegisterFile("phonebook.proto", fileDescriptor_34db5399df65ad55) }

var fileDescriptor_34db5399df65ad55 = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x65, 0x57, 0x75, 0x92, 0xa1, 0x4d, 0x60, 0x25, 0x4a, 0x6a, 0x5a, 0x5a, 0x2d, 0x12,
	0x6a, 0x2b, 0x12, 0x4b, 0x20, 0x71, 0x28, 0x27, 0x8a, 0x84, 0xd4, 0x03, 0x7f, 0x64, 0x2e, 0x48,
	0x1c, 0x22, 0x27, 0x3b, 0x71, 0x56, 0x69, 0x76, 0xc2, 0xae, 0x9d, 0x22, 0x10, 0x17, 0x5e, 0x81,
	0xb7, 0xe1, 0x35, 0x78, 0x00, 0x24, 0xc4, 0x83, 0x20, 0xaf, 0xdd, 0xc5, 0x86, 0xf4, 0x66, 0xcf,
	0x7c, 0xfb, 0xfd, 0x76, 0xbe, 0x59, 0xe8, 0x2d, 0x67, 0xa4, 0x70, 0x4c, 0x34, 0x1f, 0x2e, 0x35,
	0x65, 0xc4, 0x3a, 0xae, 0x10, 0xee, 0xa5, 0x44, 0xe9, 0x05, 0x46, 0xc9, 0x52, 0x46, 0x89, 0x52,
	0x94, 0x25, 0x99, 0x24, 0x65, 0x4a, 0x61, 0xf8, 0x24, 0x95, 0xd9, 0x2c, 0x1f, 0x0f, 0x27, 0xb4,
	0x88, 0x16, 0x97, 0x32, 0x9b, 0xd3, 0x65, 0x94, 0xd2, 0xc0, 0x36, 0x07, 0xab, 0xe4, 0x42, 0x8a,
	0x24, 0x23, 0x6d, 0x22, 0xf7, 0x59, 0x9e, 0xe3, 0x4f, 0xa1, 0xfb, 0x42, 0x2a, 0xf1, 0x5a, 0x61,
	0x8c, 0x1f, 0x72, 0x34, 0x19, 0x3b, 0x86, 0x2d, 0x0b, 0x1d, 0xa9, 0x7c, 0x31, 0x46, 0xdd, 0xf7,
	0x0e, 0xbd, 0xa3, 0xce, 0x59, 0xf0, 0xeb, 0xe7, 0x81, 0xff, 0xce, 0x8b, 0x6f, 0xd8, 0xde, 0x2b,
	0xdb, 0xe2, 0xc7, 0xd0, 0x73, 0x87, 0xcd, 0x92, 0x94, 0x41, 0xb6, 0x03, 0x01, 0x7e, 0x94, 0x26,
	0x33, 0xf6, 0x5c, 0x3b, 0xae, 0xfe, 0xf8, 0x00, 0xba, 0x31, 0x1a, 0xd4, 0x2b, 0xc7, 0xb9, 0x0b,
	0x9d, 0x44, 0x63, 0x32, 0x9a, 0x90, 0x40, 0x2b, 0xde, 0x8c, 0xdb, 0x45, 0xe1, 0x39, 0x09, 0xe4,
	0x2f, 0xa1, 0xe7, 0xe4, 0x95, 0xf3, 0x7d, 0xd8, 0xae, 0xdf, 0xab, 0x00, 0x6c, 0x1c, 0x75, 0xe2,
	0xad, 0xda, 0x85, 0x0c, 0xbb, 0x0d, 0x81, 0xc6, 0xe9, 0x48, 0x8a, 0xbe, 0x5f, 0x5c, 0x3b, 0xde,
	0xd4, 0x38, 0x3d, 0x17, 0xfc, 0x13, 0x6c, 0x3f, 0x33, 0x46, 0xa6, 0xea, 0x0a, 0x7e, 0x00, 0xad,
	0xdc, 0xa0, 0x2e, 0x84, 0x16, 0xed, 0xe6, 0x0b, 0x8a, 0xf2, 0xb9, 0xf8, 0x2f, 0x05, 0xff, 0xda,
	0x14, 0xd8, 0xbe, 0x63, 0x6e, 0x34, 0x44, 0x15, 0xfb, 0x21, 0x74, 0xaf, 0xd8, 0xd5, 0x24, 0x21,
	0xb4, 0x13, 0x5b, 0x41, 0x51, 0xa5, 0xe4, 0xfe, 0x1f, 0x7d, 0xf7, 0xe1, 0xe6, 0x9b, 0xc2, 0xfc,
	0x8c, 0x68, 0xfe, 0x16, 0xf5, 0x4a, 0x4e, 0x90, 0xcd, 0xa0, 0x55, 0xe5, 0xcc, 0x76, 0x87, 0x7f,
	0x9f, 0x48, 0x73, 0x71, 0x61, 0xb8, 0xae, 0x55, 0x22, 0xf9, 0x83, 0xaf, 0x3f, 0x7e, 0x7f, 0xf3,
	0x0f, 0xd9, 0xbd, 0xc8, 0x69, 0xa2, 0xa9, 0x54, 0x22, 0xfa, 0x5c, 0x9f, 0xf2, 0x0b, 0x1b, 0x41,
	0xab, 0xca, 0xbd, 0x41, 0x6a, 0xae, 0xae, 0x41, 0xfa, 0x67, 0x4d, 0x7c, 0xdf, 0x92, 0xee, 0x70,
	0x56, 0x23, 0xe9, 0x52, 0x73, 0xea, 0x9d, 0xb0, 0xf7, 0x10, 0x94, 0x69, 0xb0, 0x7e, 0xcd, 0xa4,
	0xb1, 0x9c, 0x70, 0x77, 0x4d, 0xa7, 0x72, 0xdf, 0xb3, 0xee, 0x3b, 0xfc, 0x56, 0xcd, 0xbd, 0xcc,
	0xee, 0xd4, 0x3b, 0x19, 0x07, 0xf6, 0x4d, 0x3f, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x33, 0x6b,
	0x6a, 0xeb, 0x47, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PhoneBookServiceClient is the client API for PhoneBookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhoneBookServiceClient interface {
	// FindOne method finds if the given phone number exists or not
	FindOne(ctx context.Context, in *FindOneRequest, opts ...grpc.CallOption) (*FindOneResponse, error)
	// Reserve method reservers 5 (unassigned) phone numbers
	//  and allow the user to choose one of them.
	//
	// The refID (random hash) is used identify the reserved numbers
	//  when Assign method is called later.
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error)
	// Assign method assigns the choosen number to the user.
	//
	// It is called immediately after Reserve method to carry on the phone number assignment.
	Assign(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*AssignResponse, error)
}

type phoneBookServiceClient struct {
	cc *grpc.ClientConn
}

func NewPhoneBookServiceClient(cc *grpc.ClientConn) PhoneBookServiceClient {
	return &phoneBookServiceClient{cc}
}

func (c *phoneBookServiceClient) FindOne(ctx context.Context, in *FindOneRequest, opts ...grpc.CallOption) (*FindOneResponse, error) {
	out := new(FindOneResponse)
	err := c.cc.Invoke(ctx, "/phonebook.PhoneBookService/FindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneBookServiceClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error) {
	out := new(ReserveResponse)
	err := c.cc.Invoke(ctx, "/phonebook.PhoneBookService/Reserve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneBookServiceClient) Assign(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*AssignResponse, error) {
	out := new(AssignResponse)
	err := c.cc.Invoke(ctx, "/phonebook.PhoneBookService/Assign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhoneBookServiceServer is the server API for PhoneBookService service.
type PhoneBookServiceServer interface {
	// FindOne method finds if the given phone number exists or not
	FindOne(context.Context, *FindOneRequest) (*FindOneResponse, error)
	// Reserve method reservers 5 (unassigned) phone numbers
	//  and allow the user to choose one of them.
	//
	// The refID (random hash) is used identify the reserved numbers
	//  when Assign method is called later.
	Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error)
	// Assign method assigns the choosen number to the user.
	//
	// It is called immediately after Reserve method to carry on the phone number assignment.
	Assign(context.Context, *AssignRequest) (*AssignResponse, error)
}

// UnimplementedPhoneBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPhoneBookServiceServer struct {
}

func (*UnimplementedPhoneBookServiceServer) FindOne(ctx context.Context, req *FindOneRequest) (*FindOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (*UnimplementedPhoneBookServiceServer) Reserve(ctx context.Context, req *ReserveRequest) (*ReserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reserve not implemented")
}
func (*UnimplementedPhoneBookServiceServer) Assign(ctx context.Context, req *AssignRequest) (*AssignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Assign not implemented")
}

func RegisterPhoneBookServiceServer(s *grpc.Server, srv PhoneBookServiceServer) {
	s.RegisterService(&_PhoneBookService_serviceDesc, srv)
}

func _PhoneBookService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneBookServiceServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.PhoneBookService/FindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneBookServiceServer).FindOne(ctx, req.(*FindOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhoneBookService_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneBookServiceServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.PhoneBookService/Reserve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneBookServiceServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhoneBookService_Assign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneBookServiceServer).Assign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.PhoneBookService/Assign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneBookServiceServer).Assign(ctx, req.(*AssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhoneBookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phonebook.PhoneBookService",
	HandlerType: (*PhoneBookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindOne",
			Handler:    _PhoneBookService_FindOne_Handler,
		},
		{
			MethodName: "Reserve",
			Handler:    _PhoneBookService_Reserve_Handler,
		},
		{
			MethodName: "Assign",
			Handler:    _PhoneBookService_Assign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phonebook.proto",
}
