apiVersion: v1
kind: Service
metadata:
  name: phonebook-service
  labels:
    app: phonebook
spec:
  # ClusterIP is for internal communication only.
  type: ClusterIP
  selector:
    app: phonebook
  ports:
    - port: 50051
      targetPort: 50051